CREATE TABLE [dbo].[Catalog_Products]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[ProductCode] VARCHAR(50) NOT NULL,
    [CategoryId] INT NOT NULL, 
    [Title] NVARCHAR(200) NOT NULL, 
    [Description] NTEXT NULL, 
	[BrandId] INT NULL,
    [ImageUrl] VARCHAR(250) NULL, 
    [Stock] INT NOT NULL DEFAULT -1, 
    [SearchText] NVARCHAR(255) NULL, 
    [Price1] MONEY NOT NULL DEFAULT 0, 
    [Price2] MONEY NULL, 
    [Price3] MONEY NULL, 
    [Price4] MONEY NULL, 
    [Price5] MONEY NULL,
	[TaxGroup] INT NOT NULL, 
    [Status] SMALLINT NOT NULL DEFAULT 1, 
    [IsFeatured] BIT NOT NULL DEFAULT 0, 
    [IsNew] BIT NOT NULL DEFAULT 0, 
    [MetaTitle] NVARCHAR(100) NULL, 
    [MetaKeywords] NVARCHAR(150) NULL, 
    [MetaDescription] NVARCHAR(250) NULL, 
    [MaxInstallment] INT NOT NULL DEFAULT 0, 
    [ShortDescription] NTEXT NULL, 
    [ManagerNotes] NTEXT NULL, 
    [IsHomepage] BIT NOT NULL DEFAULT 0, 
    [SKU] VARCHAR(25) NULL, 
    [MPN] VARCHAR(25) NULL, 
    [Barcode] NVARCHAR(250) NULL, 
    [IsBuyable] BIT NOT NULL DEFAULT 1, 
    [IsShipable] BIT NOT NULL DEFAULT 1, 
    [IsFreeShip] BIT NOT NULL DEFAULT 0, 
    [Tare] FLOAT NOT NULL DEFAULT 0, 
    [ExternalRef1] NVARCHAR(250) NULL, 
    [ExternalRef2] NVARCHAR(250) NULL, 
    [ExternalRef3] NVARCHAR(250) NULL, 
    [MetaUrl] VARCHAR(250) NULL 
    
)
